# Generated by Django 5.1.1 on 2024-10-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0003_cart_order_alter_customer_userid_customer_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userid',
            new_name='user',
        ),
    ]
