# Generated by Django 5.1.1 on 2024-10-26 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0005_remove_cart_product_id_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartline',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzashopapp.product'),
        ),
    ]
